### ISSUE TITLE
Like to know

### ISSUE THREAD

**Issue by LordAkeem** [AqFad2811/myiptv#1]
Hi bro, I like to know where do u get the license key. Iam also trying to find on my axtr go I can find first half the key after ':' this I can't find. How? Can u share with us
https://github.com/AqFad2811/myiptv/blob/4003f8d12e1e416ca8ec9141fd03ab96a1228a2b/astroandunifi-kodi#L5

**Comment by AqFad2811** [comment]
> Hi bro, I like to know where do u get the license key. Iam also trying to find on my axtr go I can find first half the key after ':' this I can't find. How? Can u share with us
> https://github.com/AqFad2811/myiptv/blob/4003f8d12e1e416ca8ec9141fd03ab96a1228a2b/astroandunifi-kodi#L5

It's actually made by someone on this Telegram, named @DannGamerz.
![Screenshot 2021-09-09 144122](https://user-images.githubusercontent.com/85995579/132635920-f4e3ea7b-9a3f-490f-b729-733db3e6f253.png)
If you want "some" of the AOTG links, just ask him.
